### PR TITLE
Update energy_day to work with energy dashboard

### PR DESCRIPTION
**Pull request by freaksdotcom**
Update the device class and state_class so the integration can be used with HA's energy dashboard.

Additional improvements:
1. Format using `black`
1. Run `isort` on includes.
1. Add type hints in some places.
1. Remove unused includes.
2. Define `OFFSET_SECONDS` using `datetime.timedelta` to make the value and units clearer.
3. Sort globals by name
4. Use a `NamedTuple` for config metadata for attribute access to fields.
5. Use f-strings instead of `str.format()`

### CODE REVIEW

**Comment by skelgaard** [comment]
i will test it out and look into it tomorrow :)

**Comment by skelgaard** [comment]
there is some sort of bug for sure... i can't see any production today and there is production

**Comment by icecreamfarmer** [comment]
> There's a bug in this PR, I'll sort it out and send an update. With the fixes it's working quite well though.
> 
> image

Has this now been resolved or integrated. Because it doesn't work with my fresh install.

**Comment by skelgaard** [comment]
no there is still bugs in this, but i have taken the good parts and build it in manually in my version and will put that in the next version

**Pull request closed without merging**
